name: Build and Push Docker image to Azure Container Registry

on:
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: products-microservice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker image
        run: |
          ACR_IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME
          BRANCH_TAG=${{ github.ref_name }}
          UNIQUE_TAG=${{ github.run_number }}

          docker build -f eCommerce.ProductsService.API/Dockerfile \
            -t $ACR_IMAGE_NAME:$BRANCH_TAG \
            -t $ACR_IMAGE_NAME:$BRANCH_TAG-$UNIQUE_TAG .

          docker push $ACR_IMAGE_NAME:$BRANCH_TAG
          docker push $ACR_IMAGE_NAME:$BRANCH_TAG-build-$UNIQUE_TAG
